extends Handler
class_name EffectHandler


## Tick counter per active application.
var _tick_counters: Dictionary = {}

## Instant applications awaiting their single processing pass.
var _pending_instant: Array[EffectApplication] = []


## Advances the effect processing by one StateModule tick and returns the effects
## generated by due applications and by pending instant applications.
func process() -> Array[Effect]:
	var effects: Array[Effect] = []
	effects.append_array(_process_pending_instant())
	effects.append_array(_process_applications())
	return effects


## Submits an instant application to be processed once on the next tick, then discarded.
func submit_instant(application: EffectApplication) -> void:
	_pending_instant.append(application)


## Removes the given applications and their processing state from this handler.
func remove_applications(applications: Array[EffectApplication]) -> void:
	for application in applications:
		remove(application)
		_tick_counters.erase(application)


## Processes pending instant applications once and returns their effects.
func _process_pending_instant() -> Array[Effect]:
	var effects: Array[Effect] = []
	for application in _pending_instant:
		var effect: Effect = application.generate_effect()
		if effect != null:
			effects.append(effect)
	_pending_instant.clear()
	return effects


## Processes active applications, returning the effects of those whose rate is reached.
func _process_applications() -> Array[Effect]:
	var effects: Array[Effect] = []
	for application in get_elements():
		var counter: int = _tick_counters.get(application, 0) + 1
		if counter >= application.rate:
			_tick_counters[application] = 0
			var effect: Effect = application.generate_effect()
			if effect != null:
				effects.append(effect)
		else:
			_tick_counters[application] = counter
	return effects