extends Module
class_name StateModule


## Emitted after a condition has been added to this state module.
signal condition_added(condition: Condition)

## Emitted after a condition has been removed from this state module.
signal condition_removed(condition: Condition)

## Emitted after a resolved effect has been applied to the entity's status.
signal effect_applied(effect: Effect)


## Conditions acquired by the entity.
var _condition_handler: ConditionHandler

## Active effect applications and their processing.
var _effect_handler: EffectHandler

## Identifiers of conditions whose effect applications are already registered.
var _activated_condition_ids: Dictionary = {}


## Creates a new state module bound to the given entity.
func _init(p_entity: Entity) -> void:
	super(p_entity)
	_condition_handler = ConditionHandler.new()
	_effect_handler = EffectHandler.new()


## Returns the pipeline phases this module participates in.
func _get_phase_callbacks() -> Array[PhaseCallback]:
	return [PhaseCallback.new(UpdatePipeline.Phase.STATE, tick)]


## Advances the state module by one tick.
func tick() -> void:
	_decay_conditions()
	_remove_dead_conditions()
	_activate_new_conditions()
	_process_effects()


## Resolves the condition in the context of its entity and adds it to this state
## module when the resolver accepts it.
func add_condition(condition: Condition) -> void:
	var resolved := entity.resolvers.condition.resolve(condition)
	if resolved == null:
		return
	_condition_handler.add_condition(resolved)
	condition_added.emit(resolved)


## Returns the condition handler of this state module.
func get_condition_handler() -> ConditionHandler:
	return _condition_handler


## Returns the effect handler of this state module.
func get_effect_handler() -> EffectHandler:
	return _effect_handler


## Applies the decay of every condition for this tick.
func _decay_conditions() -> void:
	for condition in _condition_handler.get_conditions():
		condition.decay()


## Registers the effect applications of conditions that are alive but not yet activated.
func _activate_new_conditions() -> void:
	for condition in _condition_handler.get_conditions():
		if condition.is_alive() and not _activated_condition_ids.has(condition.id):
			_activated_condition_ids[condition.id] = true
			for application in condition.get_effect_applications():
				_effect_handler.add(application)


## Removes conditions that are no longer alive together with their registered applications.
func _remove_dead_conditions() -> void:
	for condition in _condition_handler.get_conditions():
		if not condition.is_alive():
			_effect_handler.remove_applications(condition.get_effect_applications())
			_condition_handler.remove_condition(condition)
			_activated_condition_ids.erase(condition.id)
			condition_removed.emit(condition)


## Processes the effects generated by due applications: resolves each one in the
## context of its entity and applies the result to the entity's status.
func _process_effects() -> void:
	var status := entity.modules.status.get_status()
	for effect in _effect_handler.process():
		var resolved := entity.resolvers.effect.resolve(effect)
		if resolved != null and status.modify_attribute(resolved.target, resolved.value):
			effect_applied.emit(resolved)